branches:
    only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

git:
    depth: 99999999

julia:
    - "1.0"
    - "1.1"
    - "1.2"
    - "1.3"
    - "nightly"

language: julia

matrix:
    fast_finish: true

notifications:
    email:
        on_success: never # default: change
        on_failure: always # default: always

os:
    - linux
    - osx
    - windows

script: julia --code-coverage --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
