#!/bin/bash

set -ev

echo $TRAVIS_PULL_REQUEST
echo $TRAVIS_PULL_REQUEST_BRANCH
echo $TRAVIS_PULL_REQUEST_SHA
echo $TRAVIS_PULL_REQUEST_SLUG

echo $TRAVIS_COMMIT_MESSAGE
echo $TRAVIS_COMMIT
echo $TRAVIS_COMMIT_RANGE

exit 1
