function fit! end
function get_history end
function get_underlying end
function parse_functions! end
function predict end
function predict_proba end
function set_feature_contrasts! end
function set_max_epochs! end
function simple_linear_regression end
function transform end
